chore(service): add rqmetrics to deployment
SwissDataScienceCenter/renku-python pull request #1480
Opened 2020-08-19 06:58 UTC by jsam

closes: #1419

TODO:
- needs rebase to renku account on docker hub before merge

2020-08-19 13:00 UTC, rokroskar commented on helm-chart/renku-core/templates/deployment.yaml
> +
does this need annotations to be picked up by prometheus?

2020-08-19 15:57 UTC, rokroskar commented on helm-chart/renku-core/templates/deployment.yaml
> +
actually I guess they're needed in the service: https://github.com/SwissDataScienceCenter/renku-graph/blob/master/helm-chart/renku-graph/templates/event-log-service.yaml#L10-L13

2020-10-01 16:03 UTC, rokroskar requested changes

2020-10-01 16:03 UTC, rokroskar commented on helm-chart/renku-core/templates/deployment.yaml
> +          image: "justsam/rqmetrics:latest"
This needs to be templated, e.g.

```
image: {{ .Values.metrics.image }}
```

2020-10-01 16:03 UTC, rokroskar commented on helm-chart/renku-core/templates/deployment.yaml
> +          imagePullPolicy: {{ .Values.image.pullPolicy }}
```suggestion
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
```

2020-10-01 16:03 UTC, rokroskar commented on helm-chart/renku-core/templates/deployment.yaml
> +        - name: {{ .Chart.Name}}-rqmetrics
This should be in an `if` block, e.g.

```
{{ if .Values.metrics.enabled }}
```

2020-10-01 16:27 UTC, rokroskar requested changes

2020-10-01 16:27 UTC, rokroskar commented on helm-chart/renku-core/templates/deployment.yaml
> +        prometheus.io/port: '9005'
```suggestion
        prometheus.io/port: '8765'
```

2020-10-05 09:19 UTC, Panaetius approved these changes
🚀

2020-10-05 10:34 UTC, rokroskar requested changes

2020-10-05 10:34 UTC, rokroskar commented on helm-chart/renku-core/values.yaml
> +  enabled: true
usually the convention is to have metrics exporting default to false - can we do the same here?

2020-10-13 11:18 UTC, rokroskar approved these changes
Thanks @jsam, nothing quite as satisfying as watching a dashboard do its thing! :)

2020-11-03 15:28 UTC, merged