chore: chart version bump
SwissDataScienceCenter/renku-python pull request #1644
Opened 2020-10-28 22:19 UTC by rokroskar

2020-10-29 09:53 UTC, jsam approved these changes

2020-10-30 08:28 UTC, Panaetius requested changes
Some comment as to why this is done and if it is linked with an issue should be in the PR description at the very least. Otherwise it's impossible for others to know why this was done.

2020-10-30 08:42 UTC, rokroskar commented
I thought it was obvious 😄

2020-10-30 12:37 UTC, rokroskar commented
@Panaetius I updated the description - I hope it's clear enough?

2020-10-30 13:43 UTC, Panaetius approved these changes

2020-10-30 14:41 UTC, merged