chore: updates licensce headers for 2021
SwissDataScienceCenter/renku-python pull request #1861
Opened 2021-02-04 15:46 UTC by jsam

2021-02-04 16:11 UTC, Panaetius requested changes

2021-02-04 16:11 UTC, Panaetius commented on tests/core/commands/providers/test_dataverse.py
> +# 2021Swiss Data Science Center (SDSC)
This one is borked

2021-02-04 16:15 UTC, jsam commented on tests/core/commands/providers/test_dataverse.py
> +# 2021Swiss Data Science Center (SDSC)
Oops. Thanks for catching it.

2021-02-05 08:04 UTC, Panaetius approved these changes
Thank you :pray:

2021-02-05 08:09 UTC, merged