feat(core): add graph workflow group and remove subcommand
SwissDataScienceCenter/renku-python pull request #2177
Opened 2021-06-17 07:09 UTC by vigsterkr

# Description

Fixes #2081

2021-06-17 07:19 UTC, vigsterkr commented
had to restart workflows as one failed due to some VM connection issues (unrelated to renku)

2021-06-17 13:02 UTC, Panaetius requested changes
Nice work. I think we should also check on `renku run` that a name is not already in use (i.e. a plan with that name that isn't invalidated exists).

2021-06-17 13:15 UTC, vigsterkr commented on renku/core/incubation/graph.py
> +    if not force:
yeah i was contemplating with this option as well. 👍

2021-06-18 09:00 UTC, Panaetius approved these changes
Looks great now, thank you!

2021-06-18 09:15 UTC, merged