improvement(core): align commit messages made by the service
SwissDataScienceCenter/renku-python pull request #2234
Opened 2021-07-29 15:28 UTC by lorenzo-cavazzi

/deploy
fix #2152

2021-08-16 15:14 UTC, Panaetius requested changes
Looks great, thank you!

We decided a while back to switch to f-string instead of the `{0}` style syntax and we're changing it to that whenever we encounter an old style format, so there's a few places this needs to be changed. I marked some of them but there's lots :sweat_smile: 

Otherwise ready to merge

2021-08-16 15:14 UTC, Panaetius commented on renku/service/controllers/cache_migrate_project.py
> +        self.commit_message = "{0} migrate to latest version for renku {1}".format(MESSAGE_PREFIX, __version__)
use an f-string

2021-08-16 15:14 UTC, Panaetius commented on renku/service/controllers/config_set.py
> +        self.ctx["commit_message"] = "{0} config set {1}".format(
Also f-string (the ", ".join(...) will have to be done in the line above)

2021-08-16 15:14 UTC, Panaetius commented on renku/service/controllers/datasets_add_file.py
> +        self.ctx["commit_message"] = "{0} dataset add {1}".format(MESSAGE_PREFIX, self.ctx["name"])
f-string

2021-08-16 15:14 UTC, Panaetius commented on renku/service/controllers/datasets_create.py
> +        self.ctx["commit_message"] = "{0} dataset create {1}".format(MESSAGE_PREFIX, self.ctx["name"])
f-string

2021-08-16 15:14 UTC, Panaetius commented on renku/service/controllers/datasets_edit.py
> +        self.ctx["commit_message"] = "{0} dataset edit {1}".format(MESSAGE_PREFIX, self.ctx["name"])
f-string

2021-08-16 15:14 UTC, Panaetius commented on renku/service/controllers/datasets_import.py
> +        self.ctx["commit_message"] = "{0} dataset import of {1}".format(MESSAGE_PREFIX, self.ctx["dataset_uri"])
f-string

2021-08-16 16:27 UTC, lorenzo-cavazzi commented
Ouch, sorry for that.
I changed to f-strings wherever I used the `.format` notation.

2021-08-16 16:50 UTC, Panaetius commented
by the way, "improvement" isn't a tag that works in PR headers, I think. The valid ones are listed in https://github.com/SwissDataScienceCenter/renku-python/blob/master/CONTRIBUTING.rst#commit-message-guidelines (though having improvement would be nice, I think).

Not sure if the changelog generator would swallow it.

2021-08-16 17:07 UTC, rokroskar commented
I think this falls under "chore"... :)

2021-08-17 06:35 UTC, lorenzo-cavazzi commented
Oh ok, I'll stick to those listed in the readme. I'm using a plugin based on Commitizen and it lists a few others like "ci", "build", "improvement".

Not sure this is a `chore` since the change is user-facing. Shouldn't it be a `feat`? The linked docs say it's either `fix` or `feat` if the commit will end up in a changelog.

2021-08-17 09:24 UTC, Panaetius commented
feat makes sense.

Ready to merge in my view, except for the failing integration test

2021-08-17 13:14 UTC, lorenzo-cavazzi commented
I fixed the tests

2021-08-18 12:43 UTC, merged