feat(core): add project description
SwissDataScienceCenter/renku-python pull request #2235
Opened 2021-07-30 16:18 UTC by mohammad-sdsc

# Description

Can provide description when initializing a project. If project's template has a `description` attribute, this will be set as its default value and renku won't prompt for that parameter.

Fixes #2218

2021-08-16 16:05 UTC, lorenzo-cavazzi requested changes
This is a very nice addition! I added a couple of comments.

I would rather not mix this new `description` variable with the variables listed in the template manifest, and pass it to the Jinja templating system as `__description__`. That would require adapting the UI and the templates as well, but it seems a cleaner solution to me.
I'm also fine with keeping the current solution if we prefer to avoid breaking changes.

P.S. There is something that was not mentioned in the issue and is not totally clear to me. If this field should supersede the GitLab description, how should the client (i.e. UI) access this information? Should it come from the KG or should we consider adding a `project.get` endpoint?

2021-08-17 09:25 UTC, Panaetius requested changes

2021-08-17 09:27 UTC, Panaetius commented
>There is something that was not mentioned in the issue and is not totally clear to me. If this field should supersede the GitLab description, how should the client (i.e. UI) access this information? Should it come from the KG or should we consider adding a project.get endpoint?

It should be in the KG as project metadata ends up there as well

2021-08-23 19:30 UTC, mohammad-sdsc commented on renku/service/serializers/project.py
> +    AsyncSchema,
All endpoints that write to a repo support async operation including the ones that should run fast like dataset edit or setting a config. I'll keep this for now to be consistent with the rest. We can decide later which endpoints won't benefit from async execution and adjust them.

2021-08-23 19:33 UTC, mohammad-sdsc commented on renku/core/commands/init.py
> +            metadata[key] = value
The idea here was to use project description as the default value for description in the template if template has a description variable. I see your point here and agree that it's cleaner if we don't do such implicit assignment. I remove this feature and pass project's description as `__project_description__` to templates.

2021-09-03 09:28 UTC, Panaetius approved these changes

2021-09-03 12:27 UTC, lorenzo-cavazzi approved these changes
I tested a bit and all works well! Very nice addition! :+1:

2021-09-03 12:29 UTC, merged