feat(core): make rerun work with new storage
SwissDataScienceCenter/renku-python pull request #2319
Opened 2021-09-08 21:42 UTC by mohammad-sdsc

# Description

Fixes #2258

2021-09-13 09:15 UTC, Panaetius requested changes

2021-09-13 09:15 UTC, Panaetius commented on renku/core/management/interface/activity_gateway.py
> +
Should raise NotImplementedException

2021-09-13 09:15 UTC, Panaetius commented on renku/core/management/interface/activity_gateway.py
> +
Same as above

2021-09-13 16:43 UTC, mohammad-sdsc commented on renku/core/commands/rerun.py
> +    def include_newest_activity(activity):
I've added a more general utility function and used it here. There is still a duplicated line but I believe it's more readable and re-usable this way.

2021-09-14 16:34 UTC, Panaetius submitted a review, later dismissed
Thank you!

2021-09-15 07:35 UTC, Panaetius approved these changes

2021-09-15 07:37 UTC, merged