feat(dataset): use posix mv semantics when adding with destination
SwissDataScienceCenter/renku-python pull request #2612
Opened 2022-01-30 22:13 UTC by mohammad-sdsc

# Description

WIP

Fixes #1765

2022-02-08 08:23 UTC, Panaetius requested changes

2022-02-08 08:23 UTC, Panaetius commented on renku/core/management/datasets.py
> +        action = "symlink" if external else "copy"
Not something you need to change here, but `action` seems to be a good candidate for using an Enum

2022-02-08 08:23 UTC, Panaetius commented on renku/core/management/datasets.py
> +            return destination / name
```suggestion
            return destination / source_root.name if destination_exists and destination_is_dir else destination
```
Seems cleaner to me, composing a Path with an empty string seems weird to me.

2022-02-17 10:05 UTC, mohammad-sdsc commented on renku/core/utils/os.py
> +def get_files_recursively(path: Path) -> Generator[Path, None, None]:
I renamed it to `get_files`

2022-02-17 10:43 UTC, Panaetius approved these changes

2022-02-17 13:33 UTC, merged