feat(dataset): copy data to s3
SwissDataScienceCenter/renku-python pull request #3163
Opened 2022-10-11 22:56 UTC by mohammad-alisafaee

# Description

Fixes #3137 

Some refactoring in the dataset code, mainly, splitting the `ProviderApi` interface into multiple interfaces. Also, moving the `S3Storage` code to `renku.core`.

# TODO:
- Rename `dataset_provider` to `data_provider`
- Move `providers` directory from `core.dataset` to `core`

2022-11-02 15:47 UTC, Panaetius requested changes

2022-11-02 15:47 UTC, Panaetius commented on renku/core/dataset/dataset_add.py
> +        elif file.action == DatasetAddAction.METADATA_ONLY:
```suggestion
        elif file.metadata_only:
```

2022-11-02 15:47 UTC, Panaetius commented on renku/core/dataset/dataset_add.py
> +        if file.action == DatasetAddAction.REMOTE_STORAGE:
```suggestion
        if file.remote_storage:
```

2022-11-02 15:47 UTC, Panaetius commented on tests/cli/test_datasets.py
> +    } == {f.based_on.checksum for f in dataset.files}
Should we test that `upload` was called on the mocked `storage_factory` ?

2022-11-03 16:44 UTC, mohammad-alisafaee commented on renku/core/dataset/dataset_add.py
> +    NOTE: Dataset files can reside outside the dataset's datadir.
Yes. AFAIK, we don't force moving files outside the datadir to the datadir (via a migration). It's a `doctor` fix which might not be called by users. So, projects can still have files that are outside their dataset's data directory.
Although we call this function only on the new datasets with storage, we might use it at some point for the old datasets and I wanted it to be functionally correct in those cases.

2022-11-04 08:27 UTC, Panaetius approved these changes

2022-11-04 10:55 UTC, merged