feat(dataset): external storage backend
SwissDataScienceCenter/renku-python pull request #3323
Opened 2023-02-16 03:20 UTC by mohammad-alisafaee

# Description

wip

Fixes #3284

2023-03-14 14:59 UTC, Panaetius requested changes
should we separate renku.core.dataset.providers to make it clear what is for storage and what is for just add? It's getting a bit crowded in there.

And I'm a bit torn on the internal naming going from `external` to `cloud`, since it's not all cloud-based now. That could easily lead to misunderstandings. I like `external` or `remote` more

2023-03-14 14:59 UTC, Panaetius commented on renku/core/dataset/providers/api.py
> +    from typing_extensions import Protocol  # NOTE: Required for Python 3.7 compatibility
We don't support 3.7 anymore

2023-03-15 09:53 UTC, mohammad-alisafaee commented on renku/command/checks/datasets.py
> +        file_unlink(name=name, yes=True, dataset_files=files)
I believe there aren't many uses of external data (if any at all) outside our test projects. It's not worth it to do an automatic migration. We don't have a document yet for the external storages. I'll add this once we write the document.

2023-03-15 09:58 UTC, mohammad-alisafaee commented
> should we separate renku.core.dataset.providers to make it clear what is for storage and what is for just add? It's getting a bit crowded in there.

There are providers that are both storage and for add (S3, Azure, ...). I'm not sure how we can address them. I believe `renku.core.dataset.providers` isn't the best place for providers anymore. We should remove them outside the `dataset` module and put them directly under `core`. Maybe also rename them to data-provider (since we use provider in other places).

> And I'm a bit torn on the internal naming going from `external` to `cloud`, since it's not all cloud-based now. That could easily lead to misunderstandings. I like `external` or `remote` more

I changed it to cloud since I've noticed people are using this term. `Remote` makes more sense although it's a bit overused. Let's discuss this in the meeting tomorrow to decide on the terminology.

2023-03-15 10:34 UTC, Panaetius commented on renku/command/checks/datasets.py
> +        file_unlink(name=name, yes=True, dataset_files=files)
At least a sentence that it should be re-added after this would make sense to me.

2023-03-17 15:42 UTC, Panaetius approved these changes

2023-03-20 10:45 UTC, Panaetius approved these changes

2023-03-20 10:52 UTC, merged