chore: remove python 3.7 support
SwissDataScienceCenter/renku-python pull request #3344
Opened 2023-03-03 13:50 UTC by Panaetius

closes #3247 

Also bumps copyright headers.

I split it into several commits to make it easier to review (manual changes, changes done by pyupgrade to renku/ and tests/ and copyright header updates)

2023-03-03 21:53 UTC, mohammad-alisafaee requested changes
Looks great, thank you! `pyupgrade` is so cool!

We just need to remove `typing_extensions` plus a `poetry lock`

2023-03-06 08:11 UTC, Panaetius commented
I updated poetry.lock but not sure what you mean about removing typing_extensions, it's already removed

2023-03-07 10:04 UTC, mohammad-alisafaee submitted a review, later dismissed

2023-03-10 08:42 UTC, mohammad-alisafaee submitted a review, later dismissed

2023-03-10 13:14 UTC, mohammad-alisafaee approved these changes

2023-03-10 13:30 UTC, merged