feat(dataset): parallel data download/upload
SwissDataScienceCenter/renku-python pull request #3358
Opened 2023-03-11 01:32 UTC by mohammad-alisafaee

# Description

WIP

Fixes #3282

2023-03-15 10:32 UTC, Panaetius requested changes
Really nice changes, having a default implementation for parallel execution is great!

2023-03-15 10:32 UTC, Panaetius commented on renku/core/dataset/providers/web.py
> +    def download_file_wrapper(uri_filename: Tuple[str, Optional[str]], **kwargs):
if you changed it do `*d` in `parallel_execute` this wrapper wouldn't be necessary, I think

2023-03-15 10:32 UTC, Panaetius commented on renku/domain_model/constant.py
> +# Copyright 2017-2023 - Swiss Data Science Center (SDSC)
We should get rid of this/use the new header

2023-03-15 10:32 UTC, Panaetius commented on renku/core/util/util.py
> +def parallel_execute(function: Callable[..., List[Any]], *, data: List[Any], rate: float = 1, **kwargs) -> List[Any]:
Should we have a way to un-parallelize this in tests? Does it cause error to be swallowed/more difficult to debug?

2023-03-17 09:45 UTC, mohammad-alisafaee commented on renku/core/dataset/dataset.py
> +def pull_cloud_storage(name: str, location: Optional[Path] = None) -> None:
The function had it but it got misplaced.

2023-03-17 10:24 UTC, Panaetius commented on renku/core/dataset/dataset.py
>          else:
but right now it's
```
if not a or not b:
    if not a:
        [...]
    else:
        [...]
```

and I just pointed out that that's the same as
```
if not a:
    [...]
elif not b:
    [...]
```
but with less nesting

2023-03-17 11:53 UTC, mohammad-alisafaee commented on renku/core/util/util.py
> +    assert rate > 0, f"Rate must be positive: {rate}"
We should merge that PR first then.

2023-03-17 12:20 UTC, mohammad-alisafaee commented on renku/core/dataset/dataset.py
>          else:
We can write in two separate ifs but then we need to duplicate `DatasetFile` instantiation code.

2023-03-17 13:02 UTC, Panaetius commented on renku/core/dataset/dataset.py
>          else:
The way it is now is fine

2023-03-20 10:45 UTC, Panaetius submitted a review, later dismissed

2023-03-20 14:45 UTC, Panaetius approved these changes

2023-03-20 14:45 UTC, merged